ktor {
  development = true
  deployment {
    port = 8080
    watch = [build/classes/kotlin/jvm/main]
  }

  application {
    modules = [com.github.tasta_blud.darkladyblog.server.MainKt.main]
  }
}

db {
  driver = "org.h2.Driver"
  jdbcUrl = "jdbc:h2:file:~/darkladyblog;AUTO_SERVER=TRUE;"
  username = "darkladyblog"
  password = "darkladyblog"
}
